#!/bin/bash

script_version="2.12 Stable"; # 1.0 Stable

# define variable
arch_cfg=arch.cfg
debian_cfg=deb.cfg
termux_cfg=termux.cfg
fedora_cfg=fedora.cfg

ZRC=$HOME/.zshrc
BRC=$HOME/.bashrc

function distro_operation() {

	os_version=`cat /etc/os-release | grep "^ID"`
	debian=`cat /etc/os-release | grep "^ID_LIKE=debian"`
	ubuntu=`cat /etc/os-release | grep "^ID_LIKE=ubuntu"`
	arch=`cat /etc/os-release | grep "^ID_LIKE=arch"`
	default_shell=`echo "$SHELL"`;

	if [[ $os_version == "ID=fedora" ]]; then {
		
		echo "Name of Distribution  : Fedora"
		printf "Searching File        : "
		if [[ `ls -a | grep $fedora_cfg` == $fedora_cfg  ]] ; then {

			printf "Found\nDefault Shell         : ";
			if [[ $default_shell == "/bin/zsh" || $default_shell == "/usr/bin/zsh" ]]; then {
				printf "ZSH\nCloning Configuration : "; cat $fedora_cfg >> $ZRC; printf "Done\n";
			} 
			elif [[ $default_shell == "/bin/bash" || $default_shell == "/usr/bin/bash" ]]; then {
				printf "Bash\nCloning Configuration : "; cat $fedora_cfg >> $BRC; printf "Done\n";
			} 
			else printf "Failed\n"; fi

		} else echo "sorry no $input has been found"; 
		fi

	} 
	elif [[ $os_version == "ID=arch" || $arch == "ID_LIKE=arch" ]]; then {

		echo "Name of Distribution  : Arch Linux or Arch Linux Based Distribution"
		printf "Searching File        : "
		if [[ `ls -a | grep $arch_cfg` == $arch_cfg  ]] ; then {

			printf "Found\nDefault Shell         : ";
			if [[ $default_shell == "/bin/zsh" || $default_shell == "/usr/bin/zsh" ]]; then {
				printf "ZSH\nCloning Configuration : "; cat $arch_cfg >> $ZRC; printf "Done\n";
			} 
			elif [[ $default_shell == "/bin/bash" || $default_shell == "/usr/bin/bash" ]]; then {
				printf "Bash\nCloning Configuration : "; cat $arch_cfg >> $BRC; printf "Done\n";
			} 
			else printf "Failed\n"; fi

		} else echo "sorry no $input has been found"; 
		fi

	} 
	elif [[ $os_version == "ID=ubuntu" || $ubuntu == "ID_LIKE=ubuntu" ]]; then {

		echo "Name of Distribution  : Ubuntu or Ubuntu Based Linux Distribution"
		printf "Searching File        : "
		if [[ `ls -a | grep $debian_cfg` == $debian_cfg  ]] ; then {

			printf "Found\nDefault Shell         : ";
			if [[ $default_shell == "/bin/zsh" || $default_shell == "/usr/bin/zsh" ]]; then {
				printf "ZSH\nCloning Configuration : "; cat $debian_cfg >> $ZRC; printf "Done\n";
			}
			elif [[ $default_shell == "/bin/bash" || $default_shell == "/usr/bin/bash" ]]; then {
				printf "Bash\nCloning Configuration : "; cat $debian_cfg >> $BRC; printf "Done\n";
			} 
			else printf "Failed\n"; fi

		} else echo "sorry no $input has been found"; 
		fi

	} 
	elif [[ $debian == "ID_LIKE=debian" ]]; then {

		echo "Name of Distribution  : Debian Based Linux Distribution"
		printf "Searching File        : "
		if [[ `ls -a | grep $debian_cfg` == $debian_cfg  ]] ; then {

			printf "Found\nDefault Shell         : ";
			if [[ $default_shell == "/bin/zsh" || $default_shell == "/usr/bin/zsh" ]]; then {
				printf "ZSH\nCloning Configuration : "; cat $debian_cfg >> $ZRC; printf "Done\n";
			} 	
			elif [[ $default_shell == "/bin/bash" || $default_shell == "/usr/bin/bash" ]]; then {
				printf "Bash\nCloning Configuration : "; cat $debian_cfg >> $BRC; printf "Done\n";
			} 
			else printf "Failed\n"; fi

		} else echo "sorry no $input has been found"; 
		fi
		
	} 
	elif [[ `uname -o` == "Android" ]] ; then {

		termux_bash=/data/data/com.termux/files/usr/bin/bash 
		termux_zsh=/data/data/com.termux/files/usr/bin/zsh

		echo "Name of Distribution  : Android OS [Termux Environment]"
		printf "Searching File        : "
		if [[ `ls -a | grep $termux_cfg` == $termux_cfg  ]] ; then {

			printf "Found\nDefault Shell         : ";
			if [[ $default_shell == $termux_bash || $default_shell == $termux_bash ]]; then {
				printf "ZSH\nCloning Configuration : "; cat $termux_cfg >> $BRC; printf "Done\n";
			} 
			elif [[ $default_shell == $termux_zsh || $default_shell == $termux_zsh ]]; then {
				printf "Bash\nCloning Configuration : "; cat $termux_cfg >> $ZRC; printf "Done\n";
			} 
			else printf "Failed\n"; fi

		} else echo "sorry no $input has been found"; 
		fi
		
	}
	else echo "Failed to detect any distro"; fi
}

red='\033[1;91m'; green='\033[1;92m'; yellow='\033[1;93m'; stop='\e[0m';
echo 
printf "$green" && printf "CCLi$yellow v$script_version$red";
	echo "
  ____ ____ _     _
 / ___/ ___| |   (_)
| |  | |   | |   | |
| |__| |___| |___| |
 \____\____|_____|_|
	"; printf "$stop"; echo && distro_operation; echo 


## Script By Farhan Sadik
## July 2021 
### Square Development Group
