#!/bin/bash

set import busybox 
set import bash from busybox
set import git 

script_version="0.1.07";
engine_version="0.1 Alpha";

# define variable 
red='\033[1;91m'; deep_green='\033[0;32m'; green='\033[1;92m'; yellow='\033[1;93m'; blue='\033[1;94m'; white='\033[1;97m'; stop='\e[0m';
bashrc_alias=.bashrc.aliases;
arch_configuration=arch.cfg
debian_configuration=deb.cfg

# log files 
log=data.log

function FileOperation() {

	# only for bash 

	if printf "Creating Files        : "; then {
		# creating bashrc alias 
		if ls $bashrc_alias >> $log; then {
			printf "OK\n";
		}; else {
			if printf "Creating Files        : "; then touch $bashrc_alias && printf "OK\n"; fi
		}; fi
	}; fi
}
function ArchOperation() {
	if printf "Cloning Configuration : "; then {
		if less $arch_configuration >> $bashrc_alias; then {
			printf "Done\n";	
		}; fi
	}; fi;
}
function DebianOperation() {
	if printf "Cloning Configuration : "; then {
		if less $debian_configuration >> $bashrc_alias; then {
			printf "Done\n";	
		}; fi
	}; fi;	
}
function CheckDistro() {
	printf "Searching for distro  : "
	if lsb_release -i | grep 'Antergos' >> $log; then {
		printf "Found\n"; ArchOperation;
	}; elif lsb_release -i | grep 'LinuxMint' >> $log; then {
		printf "Found\n"; DebianOperation;
	}; elif lsb_release -i | grep 'ManjaroLinux' >> $log; then {
		printf "Found\n"; ArchOperation;
	}; elif lsb_release -i | grep 'Ubuntu' >> $log; then {
		printf "Found\n"; DebianOperation;
	}; else {
		sleep 0.5; printf "Failed\n";
	}; fi
}

main() {
	printf "$deep_green" && printf "CCLI$yellow v$script_version\n$red";
	figlet "CCLi" && printf "\n$stop";
}

# main logic
while true
	do
		# main # wait for user input
		# show_menu # display memu
		if main; then FileOperation && CheckDistro; fi && exit 0
done
exit 0 

# A Program By, Farhan Sadik 
# Copyright (C) Square Development Group 
