#!/bin/bash

set import busybox 
set import bash from busybox
set import git 

script_version="0.1.09 Alpha";

# define variable 
red='\033[1;91m'; deep_green='\033[0;32m'; green='\033[1;92m'; yellow='\033[1;93m'; blue='\033[1;94m'; white='\033[1;97m'; stop='\e[0m';
arch_configuration=arch.cfg
debian_configuration=deb.cfg
pc_config=/tmp/pc_config.cfg
help=help.txt
config=~/.config/ccli/

# log files 
log=/tmp/data.log

function FileOperation() {
	if printf "$yellow" && printf "Creating Files        : $red"; then {
		touch $pc_config && printf "Done\n$stop"; 
	}; fi
	if printf "$yellow" && printf "Creating Folder       : $red"; then {
		if ls ~/.config/ccli >> $log; then {
			printf "Done\n";
		}; else {
			if printf "$yellow" && printf "Creating Folder       : $red"; then {
				mkdir ~/.config/ccli && printf "Done\n$stop"; 
			}; fi
		}; fi
	}; fi
}
function ArchOperation() {
	if printf "$yellow" && printf "Cloning Configuration : $red"; then {
		if less $arch_configuration >> $pc_config; then {
			printf "Done$stop\n";	
		}; fi
	}; fi;
}
function DebianOperation() {
	if printf "$yellow" && printf "Cloning Configuration : $red"; then {
		if less $debian_configuration >> $pc_config; then {
			printf "Done$stop\n";	
		}; fi
	}; fi;	
}
function DistroOperation() {
	printf "$yellow" && printf "Searching for distro  : $red"
	if lsb_release -i | grep 'Antergos' >> $log; then {
		printf "Antergos Linux\n"; ArchOperation;
	}; elif lsb_release -i | grep 'LinuxMint' >> $log; then {
		printf "Linux Mint\n"; DebianOperation;
	}; elif lsb_release -i | grep 'ManjaroLinux' >> $log; then {
		printf "Manjaro Linux\n"; ArchOperation;
	}; elif lsb_release -i | grep 'Ubuntu' >> $log; then {
		printf "Ubuntu\n"; DebianOperation;
	}; else {
		sleep 0.5; printf "Failed\n";
	}; fi; printf "$stop"
}

main() {
	printf "$green" && printf "CCLI$yellow v$script_version$red";
	echo "
 ____ ____ _     _ 
 / ___/ ___| |   (_)
| |  | |   | |   | |
| |__| |___| |___| |
 \____\____|_____|_|
	"; printf "$stop";
	FileOperation && DistroOperation;
	printf "$yellow" && printf "Settingup Files       : $red";
	if less $pc_config >> ~/.bashrc; then printf "Done\n$stop"; fi;
	printf "$yellow" && printf "Settingup Folder      : $red";
	if cp -rfv $help $config >> $log; then printf "Done\n$stop"; fi;
	printf "$yellow" && printf "Settingup Perrmision  : $red";
	if cd $config; then chmod +x $help && printf "Done\n$stop"; fi;
}

# main logic
while true
	do
		if main; then sleep 0; fi && exit 0
done
exit 0 

# A Program By, Farhan Sadik 
# Copyright (C) Square Development Group 